"""
COMPS submission script for laser-measles beta sweep.

Adapted from run_laser_with_sif.py (cholera reference implementation).

HOW PER-SIMULATION PARAMETERS WORK
------------------------------------
COMPS executes each simulation using the command stored in WorkOrder.json, not
directly from simulation.task.command.  WorkOrder.json is generated by
add_schedule_config().

The critical rule: call add_schedule_config() ONCE PER SIMULATION inside the
sweep callback, AFTER setting simulation.task.command.  _process_simulation()
reads simulation.task.command.cmd at call time and embeds it in WorkOrder.json.

DO NOT call add_schedule_config() on the TemplatedSimulations object.  That
writes WorkOrder.json only to the base simulation; all sims deepcopy the base,
so every sim inherits the same base command regardless of per-sim task.command
overrides.  This was the root cause of all 100 sims running with beta=0.8
(the default) despite correct-looking callback code.

See README.md for full details.

Usage:
    python3.11 run_comps2.py [--num-sims N] [--pop-scale F] [--num-ticks T]
Outputs: experiment.id  (read by retrieve_outputs.py)
"""

import argparse
import os
import sys

from idmtools.assets import Asset, AssetCollection
from idmtools.core.platform_factory import Platform
from idmtools.entities import CommandLine
from idmtools.entities.command_task import CommandTask
from idmtools.builders import SimulationBuilder
from idmtools.entities.experiment import Experiment
from idmtools.entities.templated_simulation import TemplatedSimulations
from idmtools_platform_comps.utils.scheduling import add_schedule_config

# --- fixed parameters ---
SEED = 42
BETA_MIN, BETA_MAX = 0.25, 2.5
NODE_GROUP = "idm_abcd"
NUM_CORES = 4


def make_beta_values(n: int) -> list:
    if n == 1:
        return [0.8]
    return [round(BETA_MIN + i * (BETA_MAX - BETA_MIN) / (n - 1), 3) for i in range(n)]


def update_parameter_callback(simulation, beta, seed, pop_scale, num_ticks):
    """Set per-simulation command and WorkOrder.json scheduling config."""
    cmdline = (
        f"singularity exec ./Assets/laser-measles.sif"
        f" python3 ./Assets/main_measles.py"
        f" --beta {beta} --seed {seed} --pop-scale {pop_scale} --num-ticks {num_ticks}"
    )
    simulation.task.command = CommandLine(cmdline)

    # Per-sim WorkOrder.json — must be called AFTER setting task.command above.
    add_schedule_config(
        simulation,
        command=cmdline,
        NodeGroupName=NODE_GROUP,
        NumNodes=1,
        NumCores=NUM_CORES,
        Environment={"OMP_NUM_THREADS": str(NUM_CORES), "NUMBA_NUM_THREADS": str(NUM_CORES)},
    )
    return {"beta": beta, "seed": seed, "pop_scale": pop_scale, "num_ticks": num_ticks}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Submit laser-measles beta sweep to COMPS.")
    parser.add_argument("--num-sims", type=int, default=20,
                        help="Number of beta values to sweep (default 20)")
    parser.add_argument("--pop-scale", type=float, default=1.0,
                        help="Population scale factor (1.0 = ~1.2M agents)")
    parser.add_argument("--num-ticks", type=int, default=365 * 3,
                        help="Simulation length in days (default 1095 = 3 years)")
    args = parser.parse_args()

    beta_values = make_beta_values(args.num_sims)
    print(f"Submitting {args.num_sims} sim(s): beta={beta_values}, pop_scale={args.pop_scale}")

    platform = Platform("CALCULON", priority="Highest")

    # Base command — will be overridden per-sim in update_parameter_callback.
    base_cmdline = "singularity exec ./Assets/laser-measles.sif python3 ./Assets/main_measles.py"
    task = CommandTask(command=CommandLine(base_cmdline))
    # SIF from stable AssetCollection (only rebuilt when the image changes).
    task.common_assets.add_assets(AssetCollection.from_id_file("laser-measles.id"))
    # main_measles.py uploaded fresh every run — edit the script without touching the SIF.
    task.common_assets.add_asset(Asset(absolute_path=os.path.abspath("main_measles.py")))

    ts = TemplatedSimulations(base_task=task)

    sb = SimulationBuilder()
    sb.add_multiple_parameter_sweep_definition(
        update_parameter_callback,
        beta=beta_values,
        seed=[SEED],
        pop_scale=[args.pop_scale],
        num_ticks=[args.num_ticks],
    )
    ts.add_builder(sb)

    experiment = Experiment.from_template(
        ts,
        name=os.path.split(sys.argv[0])[1],
        tags={"model": "laser-measles", "sweep": "beta"},
    )
    # scheduling=True tells COMPS to use WorkOrder.json for command + scheduling.
    experiment.run(wait_until_done=True, scheduling=True)
    if experiment.succeeded:
        experiment.to_id_file("experiment.id")
        print("Experiment succeeded. ID saved to experiment.id")
    else:
        print("Experiment failed or partially failed.")
        sys.exit(1)
