[testenv:bootstrap]
deps =
    jinja2
    tox
skip_install = true
commands =
    python ci/bootstrap.py --no-env
passenv =
    *

; a generative tox configuration, see: https://tox.wiki/en/latest/user_guide.html#generative-environments
[tox]
envlist =
    clean,
    check,
    docs,
    {py310,py311,py312,py313},
    report
ignore_basepython_conflict = true

[testenv]
basepython =
    py310: {env:TOXPYTHON:python3.10}
    py311: {env:TOXPYTHON:python3.11}
    py312: {env:TOXPYTHON:python3.12}
    py313: {env:TOXPYTHON:python3.13}
    {bootstrap,clean,check,report,docs,codecov}: {env:TOXPYTHON:python3.12}
setenv =
    PYTHONPATH={toxinidir}/tests
    PYTHONUNBUFFERED=yes
    cover: SETUPPY_EXT_COVERAGE=yes
passenv =
    *
usedevelop = false
deps =
    pytest
    pytest-cov
    pytest-order
    setuptools
commands =
    {posargs:pytest --cov --cov-report=term-missing --cov-report=xml -vv tests}

[testenv:py{310,311,312,313}-ci]
basepython =
    py310-ci: {env:TOXPYTHON:python3.10}
    py311-ci: {env:TOXPYTHON:python3.11}
    py312-ci: {env:TOXPYTHON:python3.12}
    py313-ci: {env:TOXPYTHON:python3.13}
setenv =
    PYTHONPATH={toxinidir}/tests
    PYTHONUNBUFFERED=yes
    cover: SETUPPY_EXT_COVERAGE=yes
passenv =
    *
usedevelop = false
deps =
    pytest
    pytest-cov
    pytest-order
    setuptools
commands =
    {posargs:pytest --cov --cov-report=term-missing --cov-report=xml -vv -m "not slow" tests}

[testenv:check]
deps =
    docutils
    pre-commit
    readme-renderer
    pygments
    isort
skip_install = true
commands =
    # python setup.py check --strict --metadata --restructuredtext
    pre-commit autoupdate
    pre-commit run --all-files --show-diff-on-failure

[testenv:docs]
usedevelop = true
deps =
    -r{toxinidir}/docs/requirements.txt
    jupytext
commands =
    python docs/tutorials/convert_tutorials.py
    mkdocs build

[testenv:report]
deps =
    coverage
skip_install = true
commands =
    coverage report
    coverage html

[testenv:clean]
skip_install = true
deps =
    setuptools
    coverage
commands =
    coverage erase
