name: build
on:
  pull_request:
    types: [ready_for_review, review_requested, synchronize]
  push:
    branches: [ main ]
  workflow_dispatch:
    branches:
      - '*'
jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 'check'
            python: '3.12'
            toxpython: 'python3.12'
            tox_env: 'check'
            os: 'ubuntu-latest'
          - name: 'docs'
            python: '3.12'
            toxpython: 'python3.12'
            tox_env: 'docs'
            os: 'ubuntu-latest'
          - name: 'py310 (ubuntu/x86_64)'
            python: '3.10'
            toxpython: 'python3.10'
            tox_env: 'py310'
            os: 'ubuntu-latest'
          - name: 'py310 (windows/AMD64)'
            python: '3.10'
            toxpython: 'python3.10'
            tox_env: 'py310'
            os: 'windows-latest'
          - name: 'py310 (macos/arm64)'
            python: '3.10'
            toxpython: 'python3.10'
            tox_env: 'py310'
            os: 'macos-latest'
          - name: 'py314 (ubuntu/x86_64)'
            python: '3.14'
            toxpython: 'python3.14'
            tox_env: 'py314'
            os: 'ubuntu-latest'
          - name: 'py314 (windows/AMD64)'
            python: '3.14'
            toxpython: 'python3.14'
            tox_env: 'py314'
            os: 'windows-latest'
          - name: 'py314 (macos/arm64)'
            python: '3.14'
            toxpython: 'python3.14'
            tox_env: 'py314'
            os: 'macos-latest'
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - name: Install UV
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

    - name: regular build and test
      run: uvx --with tox-uv tox -e ${{ matrix.tox_env }} -v
