name: MkDocs Build on PR

on:
  pull_request:
    branches: [ master, main ]  # Replace with your desired branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install MkDocs and dependencies
      run: pip install ".[docs,examples]"

    - name: Convert tutorial .py files to notebooks
      run: python docs/tutorials/convert_tutorials.py

    - name: Build MkDocs site
      run: mkdocs build
